---
# defaults file

workdir: ~/ocp4-workdir
log_level: info
release_image_override: ""
proxy_url: ""
no_proxy: ""
enable_local_registry: false

chronyconfig:
   enabled: true

disconnected_install_registry: ""
disconnected_install_registry_cert: ""