- name: Install chrony on bastion
  yum:
    name: chrony
    state: present

- name: Open NTP port on firewall
  firewalld:
      service: ntp
      permanent: yes
      immediate: yes
      state: enabled

- name: Allow local stratum in chrony.conf on bastion
  lineinfile:
    path: /etc/chrony.conf
    regexp: '^local stratum'
    state: present
    line: "local stratum 10"
    insertafter: '^#local stratum'
    backup: yes
  notify:
    - restart chrony

- name: Allow Cluster Network in chrony.conf on bastion
  lineinfile:
    path: /etc/chrony.conf
    regexp: '^allow'
    state: present
    line: "allow {{ (ansible_default_ipv4.network + '/' + ansible_default_ipv4.netmask) | ipv4('network/prefix') }}"
    insertafter: '^#allow'
    backup: yes
  notify:
    - restart chrony

# - name: Create temporary chrony.conf file
#   template:
#     src: chrony.conf.j2
#     dest: /tmp/chrony.conf.tmp

# - name: slurp contents of temporary chrony.conf file
#   slurp:
#     src: /tmp/chrony.conf.tmp
#   register: chronybase64

# - name: Generate Chrony machineconfig
#   template:
#     src: chrony-machineconfig.j2
#     dest: "{{ workdir }}/manifests/99-{{item}}-chrony-configuration.yaml"
#   loop: 
#     - master
#     - worker

